---
- name: Start where-am-i container
  community.docker.docker_container:
    name: where-am-i
    image: "{{ where_am_i_image }}"
    state: healthy
    restart_policy: unless-stopped
    networks:
      - name: public
      - name: private
    exposed_ports:
      - 8080
    env:
      WEB_AUTHN_RP_ID: "whereami.{{ domain_name }}"
      WEB_AUTHN_ALLOWED_ORIGINS_0: "https://whereami.{{ domain_name }}"
      VIRTUAL_HOST: "whereami.{{ domain_name }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "whereami.{{ domain_name }}"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
